version: "3.8"
services:
  #
  # backend server
  #
  server:
    #restart: always
    #image: mcl_slimjre:v03
    build:
      context: ./server
      target: relay # release/artifact app stage
    ports:
      - 8080:8080
    command:
    stop_signal: SIGINT
  #
  # ...nginx
  #
  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "8083:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  #
  # frontend server
  #
  client:
    #image: mcl_slimRust:v01
    build:
      #context: ./client
      dockerfile: ./client/Dockerfile.another
      target: relay # relay release/artifact app stage
      tags:
        - "yew_mcl:01"
    command: /bin/sh -c "./trunk serve --address 0.0.0.0 --port ${TRUNK_SERVE_PORT:-8081}"
    environment:
      - SPRING_PORT=${SPRING_PORT:-8080}
      - TRUNK_SERVE_PORT=${TRUNK_SERVE_PORT:-80}
      - TRUNK_SERVE_HOST=localhost
    ports:
      - "${TRUNK_SERVE_PORT:-8081}:${TRUNK_SERVE_PORT:-8081}"
    volumes:
      - type: bind
        source: ../
        target: /app
      - yew-ui-target-cache:/app/yew-ui/target
      - yew-ui-cargo-registry-cache:/usr/local/cargo/registry
    depends_on:
      - nginx
    stop_signal: SIGINT

volumes:
  yew-ui-target-cache:
  yew-ui-cargo-registry-cache:
